AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  personalized python-serverless-api-demo

Globals:
  Function:
    Timeout: 30 

Resources:
  SimpleSummarizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        Summarize:
          Type: Api
          Properties:
            Path: /summarize
            Method: post

Outputs:
  SimpleSummarizerApi:
    Description: "API Gateway endpoint URL for SimpleSummarizer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/v0/summarize/"
