name: Run Python Tests
on:
  pull_request

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Checkout 
        # I might have to do something for the nltk data..
        uses: actions/checkout@v2
          with:
            python-version: '3.9'
            cache: 'pip'
        - run: pip install -r ./lambda-functions/requirements.txt
      - name: Run Tests
        run: python ./lambda-functions/test_get_article_contents.py