name: Python Lambda Deployment

on:
  pull_request

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-east-1
      # Build using SAM
      - run: sam build --use-container --template-file ./lambda-functions/.sam-configs/sam_build_template.yml
      # Deploy on AWS
      - run: sam deploy --config-file ./lambda-functions/.sam-configs/samconfig.toml --no-fail-on-empty-changeset --no-confirm-changeset
